import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import IdeaVaultNavbar from "@/Components/Navbar";
import IdeaVaultFooter from "@/Components/Footer";
import { ToastContainer } from "react-toastify";
import "animate.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IdeaVault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html

    
      lang="en"
      // data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <body className="min-h-full flex flex-col max-w-[2100px] mx-auto">
        <IdeaVaultNavbar/>
        <ToastContainer
      position="top-right"
      autoClose={3000}
      hideProgressBar={false}
      newestOnTop={true}
      closeOnClick
      rtl={false}
      pauseOnFocusLoss
      draggable
      pauseOnHover
      theme="dark"
    />
        <main className="min-h-[80vh]">{children}</main>
        <IdeaVaultFooter/>
      </body>
    </html>
  );
}
